version: '3.9'

services:
  database:
    image: library/postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=corporate_offers_db
    restart: on-failure
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "corporate_offers_db" ]
      interval: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DBHOST: database
    ports:
      - "5269:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres: