version: '3.9'

services:
  database:
    image: library/postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=corporate_offers_db
    restart: on-failure
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "corporate_offers_db" ]
      interval: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: